### ISSUE TITLE
deploy with flask shows error

### ISSUE THREAD

**Issue by eruvanos** [stefanhoelzl/vue.py#18]
# Steps

- install vuepy and flask
- create app.py with example code
- run `vuecli deploy flask`
- open served page

## Expected

Spinner disappears, shows example app

## Actual

Spinner stays, error on console`ModuleNotFoundError: vue`

## Extras

The setup works for the static deployment.

**Comment by stefanhoelzl** [comment]
sorry for the late response, I did not got notified about the new issue.

Thanks for reporting, I am trying to reproduce the issue!

**Comment by stefanhoelzl** [comment]
can you post your content of `app.py`? Which browser, OS and flask version are you using?

I tried with the following
```python
from vue import *

class App(VueComponent):
    template = "<div>Hello vue.py</div>"
App("#app")
```
and it worked under macOS 10.15 and Ubuntu 20.04 with Safari and Chrome

**Comment by stefanhoelzl** [comment]
I supposed this is the same issue than #27 (`ModuleNotFoundError: vue`)
This is already fixed in master.
As a workaround you can also downgrade `MarkupSafe` as described in #27
