### ISSUE TITLE
ImportError: cannot import name 'window' from 'browser'

### ISSUE THREAD

**Issue by lijiacaigit** [stefanhoelzl/vue.py#19]
ImportError: cannot import name 'window' from 'browser'

**Comment by stefanhoelzl** [comment]
how do you get this error? Can you post your `app.py`? Are you using static or flask provider?

**Comment by adamlwgriffiths** [comment]
I suspect you're running this client side, and not inside the browser with brython.

**Comment by stefanhoelzl** [comment]
closed due to inactivity
