### ISSUE TITLE
Setup.py versioning prevents updating brython

### ISSUE THREAD

**Issue by adamlwgriffiths** [stefanhoelzl/vue.py#22]
Setup.py has [brython listed with a specific version](https://github.com/stefanhoelzl/vue.py/blob/master/setup.py#L36), this creates dependency conflicts with other packages.

`install_requires=["brython==3.8.9", "Jinja2~=2.10", "pyyaml~=5.1"],`

These should be listed as >= unless there is a specific reason not to.

**Comment by stefanhoelzl** [comment]
This is intended, since `brython` often introduces breaking changes, so a specific `vuepy` version is only guaranteed to work with a specific `brython` version.

e.g. `brython==3.8.10` will `vuepy` currently, because it changed the behavior of `window.String`. This breaks the typing of props.
