### ISSUE TITLE
drop the dependencies with flask

### ISSUE THREAD

**Issue by jssuzanne** [stefanhoelzl/vue.py#3]
Hi, you made an incredible library.

my issue came from, i am **pyramid** user, and i don't want any dependencies with **flask**. 

For me, a better pattern would be to use the **extras_require** to install web application dependencies.

The **Provider class** should verify if the dependencies are satified to be used

- `pip install vuepy[flask]`: add **flask** dependencies
- `pip install vuepy[pyramid]`: add **pyramid** dependencies
- `pip install vuepy[django]`: add **django** dependencies
- `pip install vuepy[bottle]`: add **bottle** dependencies
- `pip install vuepy`: No dependencies is added, only the **Static provider** can be called

I hope, my issue is understanding.

**Comment by stefanhoelzl** [comment]
> Hi, you made an incredible library.

Thanks

will look into removing the flask dependencies.

I do not have any experience with pyramid, but feel free to add a provider :)

**Comment by stefanhoelzl** [comment]
flask is no longer needed, like you suggested with 
`pip install vuepy[flask]`
flask can be enabled

I have also changed the structure of the provider module, so that new provider can be added with little effort.

**Comment by jssuzanne** [comment]
Great.

You should replace your providerMap by entry_points. After it is becom easy for anyone to add new provider without change your code.

A little explaination of the entry proints: https://amir.rachum.com/blog/2017/07/28/python-entry-points/
In the example  the entry point use a string, it can be a class.
