### ISSUE TITLE
How to do a simple ajax request

### ISSUE THREAD

**Issue by aaronchn** [stefanhoelzl/vue.py#35]
This shouldn't be strictly an issue, it may just be a case of what I already know not being enough to implement an idea. Nonetheless, I would still like to ask for some help here, and if my request is not considered rude and excessive, I will PR to the project as much as possible once I have made some progress and learned something.

**/app.py**
```
import os, sys
root_path = os.path.abspath(os.path.join(".."))
sys.path.append(root_path)

from vue import VueComponent, VueRouter, VueRoute
from components.comm import Foo, Bar, Ping

class Router(VueRouter):
    routes = [
        VueRoute("/foo", Foo),
        VueRoute("/bar", Bar),
        VueRoute("/ping", Ping)
    ]

class App(VueComponent):
    components = [
        Ping,
    ]

    template = """
        <div>
            <p>
                <router-link to="/foo">Go to Foo</router-link>
                <router-link to="/bar">Go to Bar</router-link>
                <router-link to="/ping">Go to Ping</router-link>
            </p>
            <router-view></router-view>
        </div>
    """

App("#app" , router=Router())
```

**/components/comm.py**
```
from vue import VueComponent
from browser import ajax, alert, console

class Foo(VueComponent):
    template = "<div>foo</div>"

class Bar(VueComponent):
    msg = "Hello!"
    template = "<div><p>{{msg}}</p></div>"
    
class Ping(VueComponent):
    
    template = """
    <div>
        <button @click="greet">To greet</button>
        <button @click="doAjax">Get current time</button>
        <div><p>{{current_time}}</p></div>
    </div>
    """
    greeting = "Hello vue.py"
    current_time = ""
    url = "http://worldtimeapi.org/api/timezone/America/Los_Angeles"

    def greet(self, event):
        alert(self.greeting) 


    def doAjax(self,req):
        self.req = ajax.get(self.url, oncomplete=self.read, mode="text")
        console.log(self.req.status)

    def read(self, req):
        self.current_time = self.req.text
```

**when click the "Get current time" button:**

![ajax](https://user-images.githubusercontent.com/6897149/164491154-fda09344-2403-4184-b4ea-790448d4d22c.png)

**Comment by stefanhoelzl** [comment]
Hello,

tow things to make this work:

1)
remove the `components = [Ping]` attribute from your `App`-class. It seems there is a bug in `vuepy`, but also it is not needed in this case.

2)
rewrite your `doAjax` and `read` methods a bit
```python
def doAjax(self, ev):
    req = ajax.ajax()
    req.open("GET", self.url, True)
    req.bind("complete", self.read)
    req.send()

def read(self, ev):
    self.current_time = ev.text
```
Creating new class attributes like you did with `self.req = ...` does not work, you can only access `props` and `data` attributes. You also tried to call `url.format` but `url` was not defined (I guess this was a copy&past error).
In your `read` method you did not access the `text` attribute from the `req` parameter.
But even with fixing this, the brython specific api `ajax.get` does not work, i do not know why. But using the standard web api should work.

**Comment by aaronchn** [comment]
Yes！
It works！
