### ISSUE TITLE
How to correctly specify the --src parameter

### ISSUE THREAD

**Issue by aaronchn** [stefanhoelzl/vue.py#37]
Hi

My project structure is.
```
root
  |
  |---backend
  |    |----backend.py
  |
  |--client
  |    |----app.py
```
I tried to execute the deploy command in the root directory and the result is as follows.
![Screenshot_2022-04-29_20-57-41](https://user-images.githubusercontent.com/6897149/165979760-0850d5ae-f115-4461-933c-5554c8ec64aa.png)

Is my intent reasonable? If my intention is appropriate, please check if the --src parameter is correctly fetched by vue.py.

Thanks!

**Comment by stefanhoelzl** [comment]
try this
`vue-cli deploy --src client flask`
