### ISSUE TITLE
i am getting error while running vue-cli deploy flask

### ISSUE THREAD

**Issue by bobwatcherx** [stefanhoelzl/vue.py#47]
info

```
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/reactpy-router# python3 --version
Python 3.10.6
```

```
    from .environment import Environment
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.10/dist-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.10/dist-packages/markupsafe/__init__.py)

```

mycode
```
from vue import *

class App(VueComponent):
    template = "<div>Hello vue.py</div>"
App("#app")
```

**Comment by stefanhoelzl** [comment]
Hello,
did you install `vuepy` with `pip install vuepy`?

If so, could you please try the following:
```bash
pip uninstall vuepy
pip install "git+https://github.com/stefanhoelzl/vue.py@master#egg=vuepy[flask]"
```
your issue may be already fixed on master.

If this does not help, can you paste the output of `pip list` here?

**Comment by bobwatcherx** [comment]
yes it can be run.  but why does it take so long to load when opened in a browser

```
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/vuepy# vue-cli deploy flask
 * Serving Flask app 'vuecli.provider.flask'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [26/May/2023 08:07:55] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2023 08:07:56] "GET /vuepy.js HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2023 08:07:56] "GET /vue.js HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2023 08:07:57] "GET /loading.gif HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2023 08:07:58] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [26/May/2023 08:07:59] "GET /__entry_point__.py?1685063279542 HTTP/1.1" 200 -
127.0.0.1 - - [26/May/2023 08:07:59] "GET /app.py?v=1685063279581 HTTP/1.1" 404 -
127.0.0.1 - - [26/May/2023 08:07:59] "GET /app/__init__.py?v=1685063279689 HTTP/1.1" 404 -
127.0.0.1 - - [26/May/2023 08:07:59] "GET /Lib/site-packages/app.py?v=1685063279771 HTTP/1.1" 404 -
127.0.0.1 - - [26/May/2023 08:08:00] "GET /Lib/site-packages/app/__init__.py?v=1685063280345 HTTP/1.1" 404 -

```
my pip list
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop# pip list
Package                  Version
------------------------ -------------
aiohttp                  3.8.1
aiosignal                1.3.1
anyio                    3.6.2
appdirs                  1.4.4
apt-clone                0.2.1
apturl                   0.5.2
argcomplete              3.0.8
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asgiref                  3.6.0
asttokens                2.2.1
async-lru                2.0.2
async-timeout            4.0.2
attrs                    23.1.0
Babel                    2.12.1
backcall                 0.2.0
beautifulsoup4           4.10.0
bleach                   6.0.0
blinker                  1.6.2
branca                   0.6.0
Brlapi                   0.8.3
Brotli                   1.0.9
brython                  3.8.9
cachetools               5.3.0
ccsm                     0.9.14.1
certifi                  2020.6.20
cffi                     1.15.1
chardet                  4.0.0
charset-normalizer       2.1.1
click                    8.1.3
colorama                 0.4.4
colorlog                 6.7.0
comm                     0.1.3
command-not-found        0.3
compizconfig-python      0.9.14.1
configobj                5.0.6
coverage                 7.2.6
cryptography             3.4.8
cupshelpers              1.0
dazzler                  0.10.0
dbus-python              1.2.18
debugpy                  1.6.7
decorator                4.4.2
defer                    1.0.6
defusedxml               0.7.1
distlib                  0.3.6
distro                   1.7.0
distro-info              1.1build1
docutils                 0.20.1
EasyProcess              1.1
entrypoint2              1.1
et-xmlfile               1.1.0
exceptiongroup           1.1.1
executing                1.2.0
eyeD3                    0.8.10
fastapi                  0.95.2
fastjsonschema           2.16.3
filelock                 3.12.0
Flask                    2.3.2
Flask-Cors               3.0.10
flask-sock               0.6.0
flet                     0.7.1
flet-core                0.7.1
flet-ivid                1.2
fqdn                     1.5.1
frozenlist               1.3.3
gbinder-python           1.1.1
gpt-code-ui              0.42.29
greenlet                 2.0.1
grpcio                   1.30.2
gunicorn                 20.1.0
h11                      0.14.0
httpcore                 0.16.3
httplib2                 0.20.2
httptools                0.5.0
httpx                    0.23.3
humanize                 4.6.0
idna                     3.3
idom                     1.0.0
ifaddr                   0.1.7
imageio                  2.28.1
imageio-ffmpeg           0.4.8
IMDbPY                   2021.4.18
importlib-metadata       4.6.4
iniconfig                2.0.0
ipykernel                6.23.1
ipyleaflet               0.17.2
ipython                  8.13.2
ipython-genutils         0.2.0
ipyvue                   1.9.0
ipyvuetify               1.8.10
ipywidgets               8.0.6
isoduration              20.11.0
itsdangerous             2.1.2
jedi                     0.18.2
jeepney                  0.7.1
Jinja2                   3.1.2
json5                    0.9.14
jsonpatch                1.32
jsonpointer              2.3
jsonschema               4.17.3
jupyter_client           8.2.0
jupyter_core             5.3.0
jupyter-events           0.6.3
jupyter-lsp              2.1.0
jupyter_server           2.5.0
jupyter_server_terminals 0.4.4
jupyterlab               4.0.0
jupyterlab-pygments      0.2.2
jupyterlab_server        2.22.1
jupyterlab-widgets       3.0.7
keyring                  23.5.0
launchpadlib             1.10.16
lazr.restfulclient       0.14.4
lazr.uri                 1.0.6
louis                    3.20.0
lxml                     4.9.2
Mako                     1.1.3
Markdown                 3.4.3
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib-inline        0.1.6
mccabe                   0.7.0
mdit-py-plugins          0.3.5
mdurl                    0.1.2
mistune                  2.0.5
more-itertools           8.10.0
moviepy                  1.0.3
mss                      9.0.1
multidict                6.0.4
mutagen                  1.46.0
mypy-extensions          1.0.0
nbclassic                1.0.0
nbclient                 0.7.4
nbconvert                7.4.0
nbformat                 5.8.0
nest-asyncio             1.5.6
netaddr                  0.8.0
netifaces                0.11.0
notebook                 6.5.4
notebook_shim            0.2.3
numpy                    1.24.3
oauthlib                 3.2.2
onboard                  1.4.1
opencv-python            4.7.0.72
openpyxl                 3.1.2
packaging                23.1
pandas                   2.0.1
pandocfilters            1.5.0
parso                    0.8.3
pathspec                 0.11.1
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.0.1
pip                      22.0.2
pkginfo                  1.9.6
platformdirs             3.5.1
playwright               1.33.0
pluggy                   1.0.0
precept                  0.6.6
proglog                  0.1.10
prometheus-client        0.16.0
prompt-toolkit           3.0.38
protobuf                 3.12.4
psutil                   5.9.0
ptyprocess               0.7.0
pure-eval                0.2.2
pycairo                  1.20.1
pycodestyle              2.10.0
pycparser                2.21
pycryptodomex            3.18.0
pycups                   2.0.1
pycurl                   7.44.1
pydantic                 1.10.7
pyee                     9.0.4
pyelftools               0.27
pyflakes                 3.0.1
pygame                   2.4.0
Pygments                 2.15.1
PyGObject                3.42.0
PyICU                    2.8.1
PyJWT                    2.4.0
pymdown-extensions       10.0.1
PyNaCl                   1.5.0
pyparsing                2.4.7
pyparted                 3.11.7
pyrsistent               0.19.3
pyscreenshot             3.1
PySide6                  6.5.0
PySide6-Addons           6.5.0
PySide6-Essentials       6.5.0
PySimpleGUI              4.60.4
python-apt               2.3.0+ubuntu2
python-dateutil          2.8.2
python-debian            0.1.43ubuntu1
python-dotenv            1.0.0
python-json-logger       2.0.7
python-magic             0.4.24
python-xapp              2.2.2
python-xlib              0.29
pytz                     2023.3
pyvibe                   0.0.5
pyxdg                    0.27
PyYAML                   5.4.1
pyzmq                    25.0.2
QPUIQ                    0.2.0
reacton                  1.7.0
reactpy                  1.0.0
reactpy-router           0.0.1
readme-renderer          37.3
reloadium                1.1.1
repath                   0.9.0
reportlab                3.6.8
requests                 2.30.0
requests-file            1.5.1
requests-toolbelt        1.0.0
rfc3339-validator        0.1.4
rfc3986                  1.5.0
rfc3986-validator        0.1.1
rich                     13.3.5
rich-click               1.6.1
ruamel.yaml              0.17.26
ruamel.yaml.clib         0.2.7
SecretStorage            3.3.1
Send2Trash               1.8.2
setproctitle             1.2.2
setuptools               59.6.0
shiboken6                6.5.0
simple-websocket         0.10.0
six                      1.16.0
snakeMQ                  1.6
sniffio                  1.3.0
solara                   1.13.0
soupsieve                2.3.1
stack-data               0.6.2
starlette                0.27.0
stringcase               1.2.0
systemd-python           234
terminado                0.17.1
terminator               2.1.1
tinycss2                 1.2.1
tk                       0.1.0
tldextract               3.1.2
tomli                    2.0.1
tomlkit                  0.11.8
tornado                  6.3.2
tqdm                     4.65.0
traitlets                5.9.0
traittypes               0.2.1
trame                    2.5.0
trame-client             2.7.7
trame-components         2.1.1
trame-deckgl             2.0.2
trame-markdown           2.0.2
trame-matplotlib         2.0.2
trame-plotly             2.1.1
trame-rca                0.3.1
trame-router             2.0.2
trame-server             2.11.0
trame-simput             2.3.1
trame-vega               2.0.3
trame-vtk                2.4.4
trame-vuetify            2.2.4
typing_extensions        4.6.1
tzdata                   2023.3
ubuntu-advantage-tools   8001
ubuntu-drivers-common    0.0.0
ufw                      0.36.1
Unidecode                1.3.3
uri-template             1.2.0
urllib3                  1.26.5
uvicorn                  0.22.0
uvloop                   0.17.0
vboxapi                  1.0
virtualenv               20.23.0
vuepy                    0.4.0+581e764
wadllib                  1.3.6
watchdog                 2.3.1
watchfiles               0.19.0
watchgod                 0.8.2
wcwidth                  0.2.6
webcolors                1.13
webencodings             0.5.1
websocket-client         1.5.1
websockets               10.4
Werkzeug                 2.3.4
wheel                    0.37.1
widgetsnbextension       4.0.7
wslink                   1.10.2
wsproto                  1.2.0
xdg                      5
xkit                     0.0.0
xyzservices              2023.5.0
yarl                     1.9.2
youtube-dl               2021.12.17
yt-dlp                   2023.3.4
zipp                     1.0.0

**Comment by bobwatcherx** [comment]
and my code from you web docs
```
from browser import alert
from vue import VueComponent

class HelloVuePy(VueComponent):
    greeting = "Hello vue.py"

    def greet(self, event):
        alert(self.greeting)

    template = """
    <button @click="greet">click me</button>
    """

HelloVuePy("#app")
```
and error log browser
Traceback (most recent call last):
  File http://localhost:5000/__main__ line 1, in <module>
    import app
ModuleNotFoundError: app [vuepy.js:6254:9](http://localhost:5000/vuepy.js)
Uncaught app: 
    $factory http://localhost:5000/vuepy.js line 7929 > eval:1
    import_hooks http://localhost:5000/vuepy.js:14169
    $__import__ http://localhost:5000/vuepy.js:9468
    $import http://localhost:5000/vuepy.js:9512
    anonymous http://localhost:5000/vuepy.js line 5368 > Function:14
    loop http://localhost:5000/vuepy.js:5368
    run_script http://localhost:5000/vuepy.js:5183
    loop http://localhost:5000/vuepy.js:5376
    onreadystatechange http://localhost:5000/vuepy.js:5341
[vuepy.js line 7929 > eval:1:211](http://localhost:5000/vuepy.js%20line%207929%20%3E%20eval)
    $factory http://localhost:5000/vuepy.js line 7929 > eval:1
    import_hooks http://localhost:5000/vuepy.js:14169
    $__import__ http://localhost:5000/vuepy.js:9468
    $import http://localhost:5000/vuepy.js:9512
    anonymous http://localhost:5000/vuepy.js line 5368 > Function:14
    loop http://localhost:5000/vuepy.js:5368
    run_script http://localhost:5000/vuepy.js:5183
    loop http://localhost:5000/vuepy.js:5376
    onreadystatechange http://localhost:5000/vuepy.js:5341

**Comment by bobwatcherx** [comment]
ok it is working fine and no problem .
