### ISSUE TITLE
Vuex + javascript component

### ISSUE THREAD

**Issue by jssuzanne** [stefanhoelzl/vue.py#6]
Hi, 

I created some component in JS + ES6 + Nodejs + ... linked with Vuex.

I imported my lib, Instanced Vuex from vuepy. It does not work the error is the **$store** object is dict wrapped not an js object.

have you any solution ?

**Comment by stefanhoelzl** [comment]
converting between python objects and javascript objects sometimes leads to unexpected behavior.

I tried to write some words about this py/js bridge [here](https://stefanhoelzl.github.io/vue.py/docs/pyjs_bridge.html).

In short there is :
```python
from vue.bridge import Object
Object.to_py(obj) # converts wrapper type to native python object
Object.to_js(obj) # converts wrapper type to native js object
```

maybe you can try `Object.to_js(store)` when passing the store to vue.js

**Comment by jssuzanne** [comment]
My problem is not on the side of python but in a javascript code that uses vux. In the code js the objects are poorly formatted which makes it necessary to check if the structure is good and to correct it

**Comment by stefanhoelzl** [comment]
can you provide a minimal example that I can reproduce the bug?

**Comment by stefanhoelzl** [comment]
@jssuzanne could you checkout [this branch](https://github.com/stefanhoelzl/vue.py/tree/improved-wrapper) and test if it solves your problem?

I could reproduce a similar problem where [I tried to use a vuepy-Store by a native javascript vue component](https://github.com/stefanhoelzl/vue.py/blob/improved-wrapper/tests/selenium/test_vuex.py#L272)
In the mentioned branch I could fix this issue.
