### ISSUE TITLE
Incomplete installation instructions

### ISSUE THREAD

**Issue by volfpeter** [stefanhoelzl/vue.py#7]
According to the installation instructions, all the user has to do is pip install this project. This is not exactly true, because there is an implicit vue.js (and hence node) requirement. What makes things worse is that it only becomes apparent when the user checks why `vue-cli deploy` throws an exception (it would be nice if the exception was replaced with a simple error message saying the vue.js must be installed).

Also, it would be nice if it was in the description how `vue-cli` finds the main entry point of the application or how it can be pointed to a custom Python file.

**Comment by stefanhoelzl** [comment]
Thanks for using vue.py and pointing this out.

First there are no extra dependencies to vue.js or node. vue.py delivers everything needed to run a app.

Following the steps [here](https://stefanhoelzl.github.io/vue.py/docs/) should lead to a running app. If not can you please provide the exception traceback?

An app can only live in a `app.py`, this should be changed in the future. But for now it is static.

If you install not from pypi but the latest version directly from GitHub. Please follow this [instructions](https://stefanhoelzl.github.io/vue.py/docs/management/cli.html) for deployment.

Sorry for the inconvenience but for now there are some inconsistencies in the documentation between current release and the master-branch.

**Comment by volfpeter** [comment]
Thanks for the quick response.

Should I post support question here if there is any in the future, or should I use some other way? I would like to try to integrate [markyp-html](https://github.com/volfpeter/markyp-html) and [markyp-bootstrap4](https://github.com/volfpeter/markyp-bootstrap4) with this framework, so I guess there will be some questions eventually...

**Comment by stefanhoelzl** [comment]
Just create a new issue! So if others run into the same problem they can participate.

Maybe you can create one issue for all markyp-specific questions. And separate issues for all general questions.

**Comment by volfpeter** [comment]
Sorry, but could you reopen this issue or just fix the readme and the docs? I guess most people who have a look at the project are not vue.js developers and will end up with the mentioned crash and debugging to start with.

**Comment by volfpeter** [comment]
And thanks for the help of course!

**Comment by stefanhoelzl** [comment]
sorry, thought with your thumbs up it is fixed for you.
But you are right others might run into the same issue until it is fixed.

**Comment by volfpeter** [comment]
No problem, thanks! It's just a small usability issue, so no big deal. I just thought it's best to keep the issue open so it gets fixed sometime in the future.

Thanks again!
