### ISSUE TITLE
Vue.js and brython

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [stefanhoelzl/vue.py#9]
@stefanhoelzl Stefan: 
please share your thoughts on the following:
* https://github.com/brython-dev/brython/issues/1180
* https://github.com/brython-dev/brython/issues/1181
* https://github.com/brython-dev/brython/issues/1182
* https://github.com/brython-dev/brython/issues/1187

**Comment by stefanhoelzl** [comment]
seems like all issues mentioned here are resolved by now
